export const STRINGS = {
  LOGIN: 'Login',
  SIGNUP: 'Signup',
  HOME: 'Home',
  TODAY: 'Today',
  COMPLETED: 'Completed',
  CATEGORIES: 'Categories',
  HIGH: 'High',
  MEDIUM: 'Medium',
  LOW: 'Low',
  PERSONAL: 'Personal',
  WORK: 'Work',
  PRIORITY: 'Priority',
  CATEGORY: 'Category',
  DUE_DATE: 'Due date',
  SAVE: 'Save',
  TITLE: 'Title',
  DESCRIPTION: 'Description',
  EDIT: 'Edit',
  UPDATE: 'Update',
  OVERDUE: 'Over due',
  DATA_NOT_FOUND: 'Data Not found',
  ADD_EDIT_VIEW_TASK: 'Add/Edit/View Task',
  ERROR_MESSAGE: {
    TITLE_REQUIRED: 'Title is required',
    DESCRIPTION_REQUIRED: 'Description is required',
  },
  TWO_CATEGORIES: 'There are two categories',
};

export const NAVIGATORS = {
  LOGIN: 'LOGIN',
  SIGNUP: 'SIGNUP',
  HOME: 'HOME',
  TODAY: 'TODAY',
  COMPLETED: 'COMPLETED',
  CATEGORIES: 'CATEGORIES',
  PRIVATE: 'PRIVATE',
  ADD_EDIT_VIEW_TASK: 'ADD_EDIT_VIEW_TASK',
  PERSONAL: 'Personal',
  WORK: 'Work',
};
